### eraentals gateway deployment
#####
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: %{project_name}%-deployment
  namespace: smant
  labels:
    smant.app/name: %{project_name}%
spec:
  replicas: 1
  selector:
    matchLabels:
      smant.app/name: %{project_name}%
  template:
    metadata:
      namespace: smant
      labels:
        smant.app/name: %{project_name}%
    spec:
      containers:
        - name: %{project_name}%
          image: %{image_name}%
          resources:
            limits:
              memory: "600Mi"
              cpu: "0.8"
            requests:
              cpu: "0.5"
              memory: "400Mi"
          command: ["java","-Djava.security.egd=file:/dev/./urandom","-Dspring.profiles.active=%{active_profile}%","-jar","/app/app.jar"]
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
---
### smant crm gateway service
apiVersion: v1
kind: Service
metadata:
  name: %{project_name}%-service
  namespace: smant
  labels:
    smant.app/name: %{project_name}%
spec:
  type: ClusterIP
  selector:
    smant.app/name: %{project_name}%
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
---


