apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: erentals
data:
  filebeat.yml: |
    filebeat.inputs:
      - paths:
          - /logdata/*.log
        type: "log"
        enabled: true
        fields:
            envtag: "prod"
            podName: "${POD_NAME}"
            podIp: "${POD_IP}"
            serName: "${SERVICE_NAME}"
    output.elasticsearch:
      hosts: ["172.20.246.204:19200"]





