### deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smant-admin-gateway-deployment
  namespace: smant
  labels:
    smant.app/name: smant-admin-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      smant.app/name: smant-admin-gateway
  template:
    metadata:
      namespace: smant
      labels:
        smant.app/name: smant-admin-gateway
    spec:
      containers:
        - name: smant-admin-gateway
          image: %{image_name}%
          resources:
            limits:
              memory: "1500Mi"
              cpu: "1.5"
            requests:
              cpu: "0.8"
              memory: "1000Mi"
          command: ["java","-Dloader.path=/app/lib","-Dspring.cloud.bootstrap.location=/app/config/bootstrap.yml","-jar","/app/smant-admin-gateway.jar"]
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: harbor-userpass
---
### smant crm gateway service
apiVersion: v1
kind: Service
metadata:
  name: smant-admin-gateway
  namespace: smant
  labels:
    smant.app/name: smant-admin-gateway
spec:
  type: ClusterIP
  selector:
    smant.app/name: smant-admin-gateway
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
#      nodePort: 32144
---


